spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allow-credentials: true
            allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE